// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArOTVT5SAltcPv8b-fvUVUje7yXyOZZlo',
    appId: '1:514299898709:web:c429355a6bdd475a58dddc',
    messagingSenderId: '514299898709',
    projectId: 'expense-tracker-1c435',
    authDomain: 'expense-tracker-1c435.firebaseapp.com',
    storageBucket: 'expense-tracker-1c435.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_mM9GoFM6L86n1Gvsp9eE1tEAEgG-Aw',
    appId: '1:514299898709:android:c35184fa5b54af0958dddc',
    messagingSenderId: '514299898709',
    projectId: 'expense-tracker-1c435',
    storageBucket: 'expense-tracker-1c435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wHnY13ep-UxtI7rPo1C3uuIv5UDYUPA',
    appId: '1:514299898709:ios:9ecdff1f5677414258dddc',
    messagingSenderId: '514299898709',
    projectId: 'expense-tracker-1c435',
    storageBucket: 'expense-tracker-1c435.appspot.com',
    iosBundleId: 'com.s4k1l.xpensa',
  );
}
